http:
  routers:
    eth1:
      entryPoints:
        - "http"
      rule: "Host(`{{env "EC_LISTEN_HOST"}}`)"
      service: eth1
    eth1-ws:
      entryPoints:
        - "http"
      rule: "Host(`{{env "EC_LISTEN_HOST"}}`) && Headers(`Connection`, `Upgrade`) && Headers(`Upgrade`, `websocket`) && HeadersRegexp(`Sec-WebSocket-Key`, `.*`)"
      service: eth1-ws
    eth2:
      entryPoints:
        - "http"
      rule: "Host(`{{env "CC_LISTEN_HOST"}}`)"
      service: eth2
  services:
    eth1:
      failover:
        healthCheck: {}
        service: eth1-main
        fallback: eth1-backup
    eth1-main:
      loadBalancer:
        healthCheck:
          path: /hooks/ec
          port: 9000
          interval: "5000ms"
          timeout: "500ms"
        servers:
          - url: {{env "EC_MAIN_SCHEME"}}://{{env "EC_MAIN_HOST"}}:{{env "EC_MAIN_PORT"}}
    eth1-backup:
      loadBalancer:
        healthCheck:
          path: /hooks/ec
          port: 9000
          interval: "5000ms"
          timeout: "500ms"
        servers:
          - url: {{env "EC_FALLBACK_SCHEME"}}://{{env "EC_FALLBACK_HOST"}}:{{env "EC_FALLBACK_PORT"}}
    eth1-ws:
      failover:
        healthCheck: {}
        service: eth1-ws-main
        fallback: eth1-ws-backup    
    eth1-ws-main:
      loadBalancer:
        healthCheck:
          path: /hooks/ec
          port: 9000
          interval: "5000ms"
          timeout: "500ms"
        servers:
          - url: {{env "EC_MAIN_SCHEME"}}://{{env "EC_MAIN_HOST"}}:{{env "EC_MAIN_WS_PORT"}}
    eth1-ws-backup:
      loadBalancer:
        healthCheck:
          path: /hooks/ec
          port: 9000
          interval: "5000ms"
          timeout: "500ms"
        servers:
          - url: {{env "EC_FALLBACK_SCHEME"}}://{{env "EC_FALLBACK_HOST"}}:{{env "EC_FALLBACK_WS_PORT"}}
    eth2:
      failover:
        healthCheck: {}
        service: eth2-main
        fallback: eth2-backup          
    eth2-main:
      loadBalancer:
        healthCheck:
          path: /hooks/cc
          port: 9000
          interval: "6000ms"
          timeout: "1500ms"
        servers:
          - url: {{env "CC_MAIN_SCHEME"}}://{{env "CC_MAIN_HOST"}}:{{env "CC_MAIN_PORT"}}
    eth2-backup:
      loadBalancer:
        healthCheck:
          path: /hooks/cc
          port: 9000
          interval: "6000ms"
          timeout: "1500ms"
        servers:
          - url: {{env "CC_FALLBACK_SCHEME"}}://{{env "CC_FALLBACK_HOST"}}:{{env "CC_FALLBACK_PORT"}}
